### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by MicroSauZe11** [HarshdeepKahlon/buildcores-public#30]
Most of the time, when I click the back arrow from one part to look at a different one, the screen freezes for around 5-15 seconds, and sometimes it just crashes. It’s not something super urgent but please fix it in the near future.

**Comment by HarshdeepKahlon** [comment]
What platform is this on?

**Comment by MicroSauZe11** [comment]
iOS

**Comment by HarshdeepKahlon** [comment]
What device and operating system are you running?

**Comment by MicroSauZe11** [comment]
I’m using an iPhone 8, iOS version 13.3.1

**Comment by HarshdeepKahlon** [comment]
Ok, I'll look into it. Do you have a screen recording of the bug?

**Comment by MicroSauZe11** [comment]
Hold on

**Comment by MicroSauZe11** [comment]
Sorry never mind, I restarted my phone and it’s working fine, must’ve been a glitch with my phone.

**Comment by HarshdeepKahlon** [comment]
Ah okay. Let me know if the issue comes up again.

**Comment by MicroSauZe11** [comment]
It happened again![image](https://user-images.githubusercontent.com/64102295/84814687-d2f41200-afdf-11ea-9f1a-032ef868bc0a.png)

**Comment by MicroSauZe11** [comment]
It happened again

**Comment by MicroSauZe11** [comment]
![Uploading 84814983...]()

**Comment by MicroSauZe11** [comment]
That’s without the crash

**Comment by MicroSauZe11** [comment]
![Uploading 84815031...]()

**Comment by MicroSauZe11** [comment]
Then it crashes when I click the back arrow

**Comment by MicroSauZe11** [comment]
It only happens when zoom in on a image and then click the x

**Comment by MicroSauZe11** [comment]
To leave the image

**Comment by HarshdeepKahlon** [comment]
I don't I can see what you uploaded. Is it a video?

**Comment by MicroSauZe11** [comment]
It wouldn’t let me upload a video

**Comment by HarshdeepKahlon** [comment]
Try using this: https://streamable.com/

**Comment by MicroSauZe11** [comment]
https://streamable.com/h7dr98

**Comment by HarshdeepKahlon** [comment]
Okay that seems really weird. What accessibility options do you have enabled?

**Comment by MicroSauZe11** [comment]
What do you mean

**Comment by MicroSauZe11** [comment]
It’s weird because to stop the frozen screen I just have to swipe down

**Comment by HarshdeepKahlon** [comment]
So after you swipe down, does everything work?

**Comment by MicroSauZe11** [comment]
It might be when I leave the image it doesn’t load the part info leaving it as a translucent page

**Comment by MicroSauZe11** [comment]
Yes

**Comment by HarshdeepKahlon** [comment]
Okay, i'll try seeing if I encounter the same bug.

**Comment by MicroSauZe11** [comment]
I have a vid comparing the loaded image and the glitched transparent one

**Comment by MicroSauZe11** [comment]
https://streamable.com/x11335

**Comment by HarshdeepKahlon** [comment]
Alright I just fixed the bug. it should be released with Update 2020.4 sometime soon.

**Comment by MicroSauZe11** [comment]
Thank you
