### ISSUE TITLE
Add support for PCPartPicker

### ISSUE THREAD

**Issue by doggoboiwastaken** [HarshdeepKahlon/buildcores-public#38]
I like to use PCPartPicker and I really love this app. I was thinking maybe the saved lists in pcp could be linked to this? I love the mobile aspect and would appreciate if this were possible.

**Comment by HarshdeepKahlon** [comment]
I also wish it was possible, but it is highly unlikely. If I could get in contact with the devs at PCPartPicker, maybe this can be discussed.
