### ISSUE TITLE
App Just Vanished?!

### ISSUE THREAD

**Issue by MicroSauZe11** [HarshdeepKahlon/buildcores-public#39]
I went to the AppStore to see if there were any good games to download when I saw that there was an update for BuildCores. I went to update the app and it said that the developer removed the app from the AppStore. I clicked on the app icon and it said it was not available. I don't know why this happened but I'd like it to be checked out.

**Comment by HarshdeepKahlon** [comment]
The update I released contained a pretty bad crash so I pulled the app until the update is approved by Apple (1-2 days). Sorry about that!

**Comment by MicroSauZe11** [comment]
Ok thanks for letting me know.
