### ISSUE TITLE
Feature: PCPartPicker Integration

### ISSUE THREAD

**Issue by helluva-engineer** [HarshdeepKahlon/buildcores-public#48]
Last one from me, was wondering if you have any plans to integrate with the PCPartPicker website:

https://pcpartpicker.com/

There are some builds that can be shared using a link. Thank you for a great app!

**Comment by HarshdeepKahlon** [comment]
Thanks for making the issues! The team at PCPartPicker aren't open to outsiders trying to integrate into their platform, so I don't expect anything coming soon on that front. The goal for this app is to eventually open source the project and allow the community to contribute to it.

**Comment by helluva-engineer** [comment]
Awesome, got all of your replies! Thank you so much, only closed this one for now.
