### ISSUE TITLE
Add ability to search manually in search bar through the community added products.

### ISSUE THREAD

**Issue by lernny** [HarshdeepKahlon/buildcores-public#50]
Love the app, but I was trying to find stuff in the community tab and there's just no way i'm scrolling through all that. Would love to see this feature added if possible.

**Comment by HarshdeepKahlon** [comment]
Coming very soon! I've been working on search for community parts and community builds. I should have a TestFlight in about 2 weeks!

**Comment by lernny** [comment]
Awesome!

**Comment by HarshdeepKahlon** [comment]
TestFlight is linked here: https://testflight.apple.com/join/HGpLSYkr. It adds search functionality and a ton more!
